ir100_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

ir100_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['left_wheel_joint']
  right_wheel: ['right_wheel_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.5]
  twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.5]
  cmd_vel_timeout: 0.25

  base_frame_id: base_link
  enable_odom_tf: true
  estimate_velocity_from_position: false

  wheel_separation: 0.336
  wheel_radius: 0.062
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier: 1.0 

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0 
      has_acceleration_limits: true
      max_acceleration       : 2.0  
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0  
      has_acceleration_limits: true
      max_acceleration       : 4.0   
